#!K:\Zip Folder\resume_analyzer_django_project\resume_analyzer\env\Scripts\python.exe

import docx2txt

if __name__ == '__main__':
    import sys
    args = docx2txt.process_args()
    text = docx2txt.process(args.docx, args.img_dir)
    output = getattr(sys.stdout, 'buffer', sys.stdout)
    output.write(text.encode('utf-8'))
